spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5
      minimum-idle: 2
    
  jpa:
    hibernate:
      ddl-auto: none  # No tocar el esquema existente
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        connection:
          autocommit: false
        
  sql:
    init:
      mode: never  # No ejecutar scripts SQL, usar datos existentes
      
  transaction:
    default-timeout: 30s

server:
  port: ${PORT:8080}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.reyesemf.gm.article: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    root: INFO